CREATE TABLE convidado(
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    nome VARCHAR(24) NOT NULL,
    email VARCHAR(1024),
    telefone VARCHAR(20),
    CONSTRAINT primary_key PRIMARY KEY (id)
);